trigger:
- dev

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
  displayName: 'Install Node.js'

- script: npm i -g npm@latest
  displayName: 'Install latest version of npm'

- script: yarn
  displayName: 'Install dependencies'

- script: yarn format:check
  displayName: 'format:check'

- script: yarn format
  displayName: 'format'

- script: yarn lint
  displayName: 'lint'

- script: yarn workspace @storify/api build
  displayName: 'build backend'

- script: yarn workspace @storify/common build
  displayName: 'build common'

- script: yarn workspace @storify/frontend build
  displayName: 'build frontend'

