version: '3.9'
services:
  postgres:
    container_name: "postgres"
    image: postgres
    env_file:
      - .env
    ports:
      - "5433:5432"
    networks:
      - web
    volumes:
      - ./.data:/var/lib/postgresql/data

      
  redis:
    image: redis:latest
    command: redis-server --requirepass ${REDIS_PASSWORD}
    env_file:
      - .env
    ports:
      - "6379:6379"
    networks:
      - web
    volumes:
      - redis-data:/data
      - redis-conf:/usr/local/etc/redis/redis.conf

  api:
    container_name: "api"
    user: node
    image: node:14
    command: "yarn workspace @storify/api2 dev"
    ports:
      - "8000:8000"
    expose:
      - 8000
    volumes:
      - .:/srv/api
    env_file:
      - .env
    working_dir: /srv/api
    depends_on:
      - postgres
    networks:
      - web

volumes:
  redis-data:
  redis-conf:

networks:
  web:
    external: true
