version: '3.9'
services:
  postgres:
    container_name: "postgres"
    restart: always
    image: postgres
    environment:
      POSTGRES_USER: storify
      POSTGRES_PASSWORD: storify
      POSTGRES_DB: storify

    ports:
      - 5432:5432
    volumes:
      - ./.data:/var/lib/postgresql/data

  redis:
    container_name: redis
    image: redis
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD}
    env_file:
      - .env
    ports:
      - 6379:6379
    expose: 
      - 6379
    volumes:
      - redis-data:/data
      - redis-conf:/usr/local/etc/redis/redis.conf
      
volumes:
  redis-data:
  redis-conf:
