version: '3.9'
services:
  backend:
    build: .
    ports:
      - 8000:8000
    volumes: 
      - .:/app
    depends_on:
      - db
      - redis

  db:
    container_name: storify-db
    image: mysql:5.7.22
    restart: always
    environment:
      MYSQL_DATABASE: storify
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .dbdata:/var/lib/mysql
    ports: 
      - 33066:3306

  redis:
    container_name: storify-redis
    image: redis:latest
    ports: 
      - 6379:6379
