version: '3'
services:
  postgres:
    container_name: postgres
    image: 'postgres:latest'
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: storify
      POSTGRES_PASSWORD: storify
      POSTGRES_DB: storify
    volumes: 
      - .dbdata:/var/lib/postgres 
    expose:
      - 5432

  redis:
    image: redis:latest
    restart: always
    command: --port 6379
    expose:
      - "6379"

    ports: 
      - 6379:6379
