version: '3'
services:
  postgres:
    container_name: postgres-storify
    image: 'postgres:latest'
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: storify
      POSTGRES_PASSWORD: storify
      POSTGRES_DB: storify
    volumes: 
      - .dbdata:/var/lib/postgres 
    expose:
      - 5432

  postgres-test:
    container_name: postgres-test
    image: 'postgres:latest'
    restart: always
    ports:
      - 5555:5432
    environment:
      POSTGRES_USER: storify
      POSTGRES_PASSWORD: storify
      POSTGRES_DB: storify
    volumes: 
      - .dbdata:/var/lib/test/postgres
    expose:
      - 5555

  redis:
    image: redis:latest
    restart: always
    command: --port 6379
    expose:
      - "6379"
    volumes: 
      - .dbdata:/var/lib/redis 
    ports: 
      - 6379:6379
