name: CI / build & test
on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev, main]
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Setup node
        uses: luke-h1/setup-node@v2
        with:
          node-version: 14      
      
      - name: Checkout
        uses: luke-h1/checkout@v2

      - name: Use latest npm version
        run: npm i -g npm@latest

      - name: Install dependencies
        run: yarn

      - name: start docker DBs
        run: yarn workspace @storify/api docker-compose up -d

      - name: format:check
        run: yarn format:check 
        
      - name: format
        run: yarn format

      - name: lint
        run: yarn lint

      - name: tsc
        run: yarn tsc

      - name: build backend
        run: yarn workspace @storify/api build 

      - name: build common
        run: yarn workspace @storify/common build 

      - name: build frontend
        run: yarn workspace @storify/frontend build 

      - name: Backend unit tests 
        run: yarn workspace @storify/api test